services:
  db:
    image: postgres:16.0-alpine3.18
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=registration_site
  mail:
    image: maildev/maildev:2.1.0
    ports:
      - 1080:1080
      - 1025:1025
  app:
    build: .
    depends_on:
      - db
      - mail
    ports:
      - 8000:8000
